[package]
name = "week-partitioner"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
macroquad = { version = "0.4.13", features = ["log-rs", "log"] }

[profile.dev.package.'*']
opt-level = 3

